export const fieldRegistry: { [key: string]: any[] } = {
    university: [
        { name: 'universityName', label: 'University Name', type: 'text', required: true },
        { name: 'country', label: 'Country', type: 'text' },
        { name: 'accreditation', label: 'Accreditation', type: 'text' },
        { name: 'email', label: 'Contact Email', type: 'email' },
    ],
    studycenter: [
        { name: 'centerName', label: 'Center Name', type: 'text', required: true },
        { name: 'location', label: 'Location/City', type: 'text' },
        { name: 'manager', label: 'Center Manager', type: 'text' },
        { name: 'phone', label: 'Phone', type: 'text' },
        { name: 'email', label: 'Email', type: 'email' },
    ],
    program: [
        { name: 'programName', label: 'Program/Course Name', type: 'text', required: true },
        { name: 'university', label: 'University', type: 'text', required: true },
        { name: 'duration', label: 'Duration (Years)', type: 'number' },
        { name: 'fees', label: 'Total Fees', type: 'number' },
        { name: 'mode', label: 'Mode', type: 'select', options: ['Online', 'Distance', 'Regular'] },
    ],
    announcement: [
        { name: 'title', label: 'Title', type: 'text', required: true },
        { name: 'content', label: 'Content / Question', type: 'textarea', required: true },
        { name: 'type', label: 'Type', type: 'select', options: ['Announcement', 'Poll'], default: 'Announcement' },
        { name: 'poll_options_text', label: 'Poll Options (For Polls: Enter one option per line)', type: 'textarea' },
        { name: 'priority', label: 'Priority', type: 'select', options: ['Low', 'Medium', 'High'], required: true },
        { name: 'department', label: 'Department', type: 'text', placeholder: 'Target Department (or leave empty for All)' },
        { name: 'startDate', label: 'Start Date (Visible From)', type: 'datetime-local', required: true },
        { name: 'endDate', label: 'End Date (Visible Until)', type: 'datetime-local', required: true },
        { name: 'pinned', label: 'Pinned', type: 'checkbox' }
    ],
    complaint: [
        { name: 'subject', label: 'Subject', type: 'text', required: true },
        { name: 'description', label: 'Description', type: 'textarea', required: true },
        { name: 'status', label: 'Status', type: 'select', options: ['Open', 'In Progress', 'Resolved', 'Dismissed'], default: 'Open' },
        { name: 'date', label: 'Date', type: 'date' },
        { name: 'employeeName', label: 'Filed By', type: 'text' }
    ],
    student: [
        { name: 'studentName', label: 'Student Name', type: 'text', required: true },
        { name: 'email', label: 'Email', type: 'email' },
        { name: 'phone', label: 'Phone', type: 'text' },
        { name: 'qualification', label: 'Last Qualification', type: 'text' },
        { name: 'status', label: 'Status', type: 'select', options: ['Inquiry', 'Verified', 'Registered', 'Admitted'] },
        { name: 'username', label: 'Portal Username', type: 'text' },
        { name: 'password', label: 'Portal Password', type: 'text' },
    ],
    application: [
        { name: 'student', label: 'Student', type: 'text', required: true },
        { name: 'program', label: 'Program Applied For', type: 'text', required: true },
        { name: 'studyCenter', label: 'Study Center', type: 'text', required: true },
        { name: 'applicationDate', label: 'Application Date', type: 'date' },
        { name: 'status', label: 'Admission Status', type: 'select', options: ['Draft', 'Submitted to University', 'Approved', 'Rejected', 'Fee Paid'] },
        { name: 'assignedTo', label: 'Assigned To (Employee ID)', type: 'text' },
    ],
    lead: [
        { name: 'leadName', label: 'Lead Name', type: 'text', required: true },
        { name: 'email', label: 'Email', type: 'email' },
        { name: 'status', label: 'Status', type: 'select', options: ['Lead', 'Open', 'Replied', 'Opportunity', 'Quotation', 'Interested', 'Converted', 'Lost Quotation', 'Do Not Contact'] },
        { name: 'assignedTo', label: 'Assigned To (Employee ID)', type: 'text' },
    ],
    employee: [
        { name: 'employeeId', label: 'Employee ID', type: 'text', required: true },
        { name: 'employeeName', label: 'Full Name', type: 'text', required: true },
        { name: 'designation', label: 'Designation', type: 'text', required: true },
        { name: 'department', label: 'Department', type: 'select', options: [], link: 'department' },
        { name: 'dateOfJoining', label: 'Date of Joining', type: 'date' },
        { name: 'status', label: 'Status', type: 'select', options: ['Active', 'On Leave', 'Resigned'] },
        { name: 'email', label: 'Email', type: 'email' },
        { name: 'username', label: 'Username (Login)', type: 'text' },
        { name: 'password', label: 'Password (Login)', type: 'text' },
        { name: 'vacancy', label: 'Vacancy (Job Opening)', type: 'select', link: 'jobopening' },
    ],
    attendance: [
        { name: 'employee', label: 'Employee ID', type: 'text', required: true },
        { name: 'employeeName', label: 'Employee Name', type: 'text', required: true },
        { name: 'date', label: 'Date', type: 'date' },
        { name: 'status', label: 'Status', type: 'select', options: ['Present', 'Absent', 'Half Day', 'On Leave'] },
    ],
    holiday: [
        { name: 'holidayName', label: 'Holiday Name', type: 'text', required: true },
        { name: 'date', label: 'Date', type: 'date', required: true },
        { name: 'description', label: 'Description', type: 'text' },
    ],
    performancereview: [
        { name: 'employee', label: 'Employee ID', type: 'text', required: true },
        { name: 'employeeName', label: 'Employee Name', type: 'text', required: true },
        { name: 'reviewCycle', label: 'Review Cycle', type: 'select', options: ['Q1 2026', 'Q2 2026', 'Annual 2025', 'Probation Review'] },
        { name: 'rating', label: 'Rating (1-5)', type: 'select', options: ['1', '2', '3', '4', '5'] },
        { name: 'feedback', label: 'Feedback/Comments', type: 'text' },
        { name: 'reviewer', label: 'Reviewer Name', type: 'text' },
        { name: 'reviewDate', label: 'Review Date', type: 'date' },
    ],
    department: [
        { name: 'name', label: 'Department Name', type: 'text', required: true },
        { name: 'code', label: 'Code', type: 'text', required: true },
        { name: 'description', label: 'Description', type: 'text' },
        { name: 'headOfDepartment', label: 'HOD Name', type: 'text' },
        { name: 'parentDepartment', label: 'Parent Department', type: 'select', options: [], link: 'department' },
    ],
    jobopening: [
        { name: 'job_title', label: 'Job Title', type: 'text', required: true },
        { name: 'department', label: 'Department', type: 'select', link: 'department' },
        { name: 'no_of_positions', label: 'Number of Positions', type: 'number', required: true },
        { name: 'status', label: 'Status', type: 'select', options: ['Open', 'Closed', 'On Hold'], default: 'Open' },
        { name: 'description', label: 'Job Description', type: 'textarea' }
    ]
};
